version: "3"
services:
  api:
    image: tzuwang0126/planus
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
